### ISSUE TITLE
Error creating Cpu instance

### ISSUE THREAD

**Issue by dbuendiab** [it-geeks-club/pyspectator#12]
```
>>> cpu = Cpu(monitoring_latency=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python35\lib\site-packages\pyspectator\processor.py", line 60, in __init__
    self.__temperature_reader = Cpu.__get_processor_temperature_reader()
  File "C:\Python35\lib\site-packages\pyspectator\processor.py", line 174, in __get_processor_temperature_reader
    reader = WindowsCpuTemperatureReader.get_reader()
TypeError: get_reader() takes 0 positional arguments but 1 was given
>>> exit()
```
I've solved it changing **@classmethod** by **@staticmethod** in **temperature_reader.py** (line 48)

```
class WindowsCpuTemperatureReader():

    @staticmethod
    def get_reader():
        import wmi
        import pythoncom
```

**Comment by uzumaxy** [comment]
Should be fixed in 1.2.0 release. Please re-open if it wasn't.
