### ISSUE TITLE
Newest version not available via pip (on Python 3.5)

### ISSUE THREAD

**Issue by Laberbear** [it-geeks-club/pyspectator#9]
Hey there, I'm trying to install pyspectator 1.1.0 on Windows10 with Python 3.5
However it seems, that the newest release isn't available there

```
$ pip install pyspectator==1.1.0
Collecting pyspectator==1.1.0
  Could not find a version that satisfies the requirement pyspectator==1.1.0 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8)
No matching distribution found for pyspectator==1.1.0
```

When installing the release manually the error is pretty simple:

```
>>> from pyspectator.computer import Computer
>>> c = Computer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\Python\Python35\lib\site-packages\pyspectator-1.1.0-py3.5.egg\pyspectator\computer.py", line 25, in __init__
  File "\Python\Python35\lib\site-packages\pyspectator-1.1.0-py3.5.egg\pyspectator\processor.py", line 60, in __init__
  File "\Python\Python35\lib\site-packages\pyspectator-1.1.0-py3.5.egg\pyspectator\processor.py", line 174, in __get_processor_temperature_reader
TypeError: get_reader() takes 0 positional arguments but 1 was given
```

The cls argument was simply forgotten there.
A small mistake but having a pip install for the newest version would greatly ease the deployment of my python app.

This is probably caused by a simple missing positional argument in processor.py:

**Comment by uzumaxy** [comment]
Hey @Laberbear ,
I've uploaded new 1.2.0 version Fix that you've described also should be included there.

Can you please check it again?

Thanks!

**Comment by uzumaxy** [comment]
Please re-open issue if you'll face with this issue again.
